server:
  port: 9000
  
  
eureka:
  client:
    service-url: 
      default-zone: http://localhost:8761
      
spring:
  application:
    name: GATEWAY
    
  cloud:
     gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      
