server:
  port: 8082
spring:

  neo4j:
       uri: bolt://localhost:7687
       
       authentication:
         username: neo4j
         password: password
       
  data:
     neo4j:
        database: base
  

  application:
    name: RETRIEVE-SERVICE
